In [1]:
import os
os.environ["Method"] = "stochastic"
import nonlinear_solver_initial as solver     #solves opt. problems for terminal VF
import nonlinear_solver_iterate as solviter   #solves opt. problems during VFI
import interpolation as interpol              #interface to sparse grid library/terminal VF
import interpolation_iter as interpol_iter    #interface to sparse grid library/iteration
import postprocessing as post
import TasmanianSG                            #sparse grid library
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import HTML

In [2]:
paramL = dict()
# Depth of "Classical" Sparse grid
paramL['iDepth']=1
paramL['iOut']=1         # how many outputs
paramL['which_basis'] = 1 #linear basis function (2: quadratic local basis)

# control of iterations
paramL['numstart'] = 0   # which is iteration to start (numstart = 0: start from scratch, number=/0: restart)
paramL['numits'] = 5    # which is the iteration to end

# How many random points for computing the errors
paramL['No_samples'] = 200

### Model Paramters
paramL['n_agents']=2  # number of continuous dimensions of the model

paramL['beta']=0.5
paramL['rho']=0.95
paramL['zeta']=0.5
paramL['psi']=0.36
paramL['gamma']=2.0
paramL['delta']=0.025
paramL['eta']=1
paramL['big_A']=(1.0-paramL['beta'])/(paramL['psi']*paramL['beta'])

# Ranges For States
paramL['range_cube']=5 # range of [0..1]^d in 1D
paramL['k_bar']=0.2
paramL['k_up']=3.0

# Ranges for Controls
paramL['c_bar']=1e-2
paramL['c_up']=10000.0

paramL['l_bar']=1e-2
paramL['l_up']=1.0

paramL['inv_bar']=1e-2
paramL['inv_up']=10000.0

# Stochastic
paramL['theta_list'] = [0.9, 0.95, 1.00, 1.05, 1.10]
paramL['curr_theta'] = 1.00

In [3]:
#valList = []
output = dict()
output[paramL['numstart']] = []
for state in range(5):
    paramL['curr_theta'] = paramL['theta_list'][state]
    valnew=TasmanianSG.TasmanianSparseGrid()
    valnew=interpol.sparse_grid(paramL)
    output[paramL['numstart']].append(TasmanianSG.TasmanianSparseGrid())
    output[paramL['numstart']][state] = valnew
    valnew.write("valnew_1." + str(paramL['numstart']) +".s{}".format(state)+ ".txt") #write file to disk for restart
    #print(valnew.evaluateBatch(valnew.getPoints()))

(array([1.6, 1.6]), array([0.25491948]))
(array([1.6, 0.2]), array([-1.15920535]))
(array([1.6, 3. ]), array([0.67441488]))
(array([0.2, 1.6]), array([-1.15920535]))
(array([3. , 1.6]), array([0.67441488]))
(array([1.6, 1.6]), array([0.45377211]))
(array([1.6, 0.2]), array([-0.87500378]))
(array([1.6, 3. ]), array([0.8538217]))
(array([0.2, 1.6]), array([-0.87500378]))
(array([3. , 1.6]), array([0.8538217]))
(array([1.6, 1.6]), array([0.63394398]))
(array([1.6, 0.2]), array([-0.61885766]))
(array([1.6, 3. ]), array([1.01639982]))
(array([0.2, 1.6]), array([-0.61885766]))
(array([3. , 1.6]), array([1.01639982]))
(array([1.6, 1.6]), array([0.79800359]))
(array([1.6, 0.2]), array([-0.38680313]))
(array([1.6, 3. ]), array([1.16446042]))
(array([0.2, 1.6]), array([-0.38680313]))
(array([3. , 1.6]), array([1.16446042]))
(array([1.6, 1.6]), array([0.94806491]))
(array([1.6, 0.2]), array([-0.17559007]))
(array([1.6, 3. ]), array([1.29990606]))
(array([0.2, 1.6]), array([-0.17559007]))
(array([

In [4]:
output[1] = []
for state in range(5):
    paramL['curr_theta'] = paramL['theta_list'][state]
    valnew=TasmanianSG.TasmanianSparseGrid()
    valnew=interpol_iter.sparse_grid_iter(paramL, output[0])
    output[1].append(TasmanianSG.TasmanianSparseGrid())
    output[1][state] = valnew
    valnew.write("valnew_1."+str(1)+".s{}".format(state)+".txt")

[0.25491948]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14063917]
[3.08870407]
1
[0.25491948]
[0.70869159]
2
[0.70869159]
[1.34263557]
3
[1.34263557]
[2.14063917]
4
[2.14

In [5]:
output[2] = []
for state in range(5):
    paramL['curr_theta'] = paramL['theta_list'][state]
    valnew=TasmanianSG.TasmanianSparseGrid()
    valnew=interpol_iter.sparse_grid_iter(paramL, output[1])
    output[2].append(TasmanianSG.TasmanianSparseGrid())
    output[2][state] = valnew
    valnew.write("valnew_1."+str(2)+".s{}".format(state)+".txt")

[-0.06397379]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.91658609]
4
[0.91658609]
[1.56012807]
1
[-0.06397379]
[0.08432074]
2
[0.08432074]
[0.41848864]
3
[0.41848864]
[0.9165860

In [8]:
print(output[0][0])
print(output[1][0])
print(output[2][0])

<TasmanianSG.TasmanianSparseGrid instance at 0x7f035ffe0200>
<TasmanianSG.TasmanianSparseGrid instance at 0x7f035fa964d0>
<TasmanianSG.TasmanianSparseGrid instance at 0x7f035fa381b8>
